name: "MQTT Presence Reporter"
version: "1.0.0"
slug: "mqtt_presence"
description: "Annuncia lo stato di Home Assistant a un broker MQTT esterno"
startup: application
boot: auto
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
options:
  device_name: ""
  mqtt_host: "your-broker"
  mqtt_port: 1883
  mqtt_username: "mqttuser"
  mqtt_password: "password"
schema:
  device_name: "str?"
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_username: "str"
  mqtt_password: "str"
